### ISSUE TITLE
Please consider naming the  commandline multidiff

### ISSUE THREAD

**Issue by yarikoptic** [juhakivekas/multidiff#2]
- for sure should not have `.py` suffix since implementation detail is not important
- would make it easier to get started using (I installed `multidiff` so I use `multidiff` instead of figuring out what is the cmdline entry point)

**Comment by juhakivekas** [comment]
This makes sense and I could do it, however I have some non-commandline ideas I want to implement, so in a sense I wouldn’t like to call the utilities something different. mdcli.py is not really intended to be all of multidiff and hats why it’s named differently.

I could rename it just for ease of use and familiarity, but I don’t expect this to be the only utility using the internals  of multidiff.

**Comment by yarikoptic** [comment]
FWIW `multidiff` could be a "gateway" command, like you use `git` with all the commands.  So you could have `multidiff action1` etc

**Comment by juhakivekas** [comment]
I made the setup.py install a command multidiff. It's practical and looks better in general :)
